#define REG_SYSTEM_SERNUM 0x02 // SERIAL NUMBER
#define REG_SYSTEM_DATE 0x10   // TANGGAL
#define REG_SYSTEM_CLOCK 0x11  // JAM

#define REG_INSTAN_PFACT 0x26 // POWER FACTOR
#define REG_INSTAN_KVARH 0x33 // KVAR

#define REG_ENERGY_KWHA 0x01 // KWH A
#define REG_ENERGY_KWHB 0x02 // KWH B
#define REG_ENERGY_KWHT 0x00 // KWH TOTAL